# Generated by Django 5.2.4 on 2025-07-07 11:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.blog_thumbnail_upload_path),
        ),
    ]
