# Generated by Django 5.2.4 on 2025-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
